name: z2jh Docker image from local repo

on:
  push:
    branches:
      - '**'

jobs:
  
  build_cdsdashboards_local:
    name: Build and Push cdsdashboards-jupyter-k8s-hub local
    runs-on: ubuntu-18.04

    steps:

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Get Short SHA
        id: getshortsha
        run: echo "::set-output name=sha_short::$(git rev-parse --short=7 ${{ github.sha }})"

      - name: Get z2jh helm chart version number
        uses: pCYSl5EDgo/cat@master
        id: z2jhverstep
        with:
          path: helm-z2jh-latest.txt
          trim: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker 
        uses: docker/build-push-action@v2
        env: 
          cds_helm_chart_ver: ${{ steps.hello.z2jhverstep.text }}
        with:
          tags: ideonate/cdsdashboards-jupyter-k8s-hub:${{ env.cds_helm_chart_ver }}-sha-${{ steps.getshortsha.outputs.sha_short }}
          context: ./
          file: ./docker-images/z2jh/hub/Dockerfile
          build-args: |
            BASE_IMAGE=jupyterhub/k8s-hub:${{ env.cds_helm_chart_ver }}
          push: ${{ github.event_name != 'pull_request' }}

          